// Frontend/Hands_On_8/src/components/CourseCard.vue
<template>
  <div class="card">
    <h3>{{ name }}</h3>

    <p>
      <strong>Code:</strong> {{ code }}
    </p>

    <p>
      <strong>Credits:</strong> {{ credits }}
    </p>

    <p>
      <strong>Grade:</strong> {{ grade }}
    </p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String
})
</script>

<style scoped>
.card {
  background: white;
  padding: 20px;
  border-radius: 12px;
  box-shadow: 0 2px 10px rgba(0,0,0,.1);
}
</style>

// Frontend/Hands_On_5/Hands_On_5/src/components/CourseCard.jsx
function CourseCard({
  id,
  name,
  code,
  credits,
  grade,
  onEnroll,
}) {
  return (
    <div className="card">
      <h3>{name}</h3>

      <p>
        <strong>Code:</strong> {code}
      </p>

      <p>
        <strong>Credits:</strong> {credits}
      </p>

      <p>
        <strong>Grade:</strong> {grade}
      </p>

      <button onClick={() => onEnroll({ id, name, code })}>
        Enroll
      </button>
    </div>
  );
}

export default CourseCard;
